# -*- coding: utf-8 -*-
"""clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n85Qq7aFIAiIs_0RlyAhnSAFPa3IByHI

# MODULE-1,2

# This cell imports all the necessary libraries for web scraping, data manipulation, and file system operations: requests for making HTTP requests, BeautifulSoup for parsing HTML, pandas for data handling, time for adding delays, and os for interacting with the operating system.
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import os

"""# This cell initializes key variables for web scraping. BASE_URL is the main page for country military rankings. OTHER_SOURCES is a dictionary where each key is a URL for a specific military metric (like 'Total Population' or 'Defense Budget'), and its corresponding value is the name you want to use for that data column. Finally, os.makedirs('html_debug', exist_ok=True) creates a folder named 'html_debug' if it doesn't already exist, which can be used to save HTML files for debugging scraped content."""

BASE_URL = "https://www.globalfirepower.com/countries-listing.php"

OTHER_SOURCES = {
    'https://www.globalfirepower.com/total-population-by-country.php': 'Total Population',
    'https://www.globalfirepower.com/available-military-manpower.php': 'Total Military Personnel',
    'https://www.globalfirepower.com/active-military-manpower.php': 'Active Personnel',
    'https://www.globalfirepower.com/active-reserve-military-manpower.php': 'Reserve Personnel',
    'https://www.globalfirepower.com/aircraft-total.php': 'Total Aircraft Strength',
    'https://www.globalfirepower.com/aircraft-helicopters-total.php': 'Total Helicopter Strength',
    'https://www.globalfirepower.com/armor-tanks-total.php': 'Total Tank Strength',
    'https://www.globalfirepower.com/navy-ships.php': 'Total Naval Assets',
    'https://www.globalfirepower.com/defense-spending-budget.php': 'Defense Budget'
}
# folder for debugging HTML (optional but recommended)
os.makedirs("html_debug", exist_ok=True)

"""# The get_soup function is a utility designed for web scraping. It takes a URL as input and performs the following actions:

It uses the requests library to send an HTTP GET request to the provided URL, simulating a web browser by setting a 'User-Agent' header. It also sets a timeout of 20 seconds to prevent indefinite waiting.
response.raise_for_status() checks if the request was successful. If there was an HTTP error (e.g., 404 Not Found, 500 Server Error), it will raise an exception.
Finally, it parses the HTML content of the response (response.text) using BeautifulSoup with the 'html.parser' to create a navigable parse tree. This BeautifulSoup object, commonly referred to as 'soup', allows for easy extraction of data from the HTML structure.
"""

def get_soup(url):
    response = requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0"},
        timeout=20
    )
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")

"""# This cell calls the get_soup function with the BASE_URL, which is https://www.globalfirepower.com/countries-listing.php. The get_soup function then fetches the HTML content from this URL, parses it using BeautifulSoup, and the result is displayed in the output. This action effectively retrieves the main page content for inspection and subsequent scraping."""

get_soup(BASE_URL)

"""# The get_country_list function is designed to scrape the main ranking page (BASE_URL) to extract each country's name, their overall rank, and their 'PowerIndex'. It does this by:

Calling get_soup(BASE_URL) to get the parsed HTML of the main page.
Selecting all div elements with the class recordsetContainer, as each of these contains data for a single country.
Iterating through each record found:
It extracts the country name from a span within div.longFormName.
It extracts the rank from a span within div.rankNumContainer.
It extracts the PowerIndex value from a span within div.pwrIndxContainer, removing the 'PwrIndx:' prefix.
It appends this data to all_country_data as a dictionary, ensuring country, rank, and pwrindx are all present before adding.
Finally, it returns a pandas.DataFrame created from all_country_data.
After defining the function, the cell calls country_df = get_country_list() to execute the scraping and store the results in the country_df DataFrame. print(country_df.head()) then displays the first few rows of this DataFrame.
"""

def get_country_list():
    soup = get_soup(BASE_URL)

    records = soup.select("div.recordsetContainer")
    all_country_data = []

    for record in records:
        country_span = record.select_one("div.longFormName > span")
        rank_container = record.select_one("div.rankNumContainer > span")
        pwrindx_container = record.select_one("div.pwrIndxContainer > span")

        country = country_span.text.strip() if country_span else None
        rank = rank_container.text.strip() if rank_container else None
        pwrindx = pwrindx_container.text.replace('PwrIndx:', '').strip() if pwrindx_container else None

        if country and rank and pwrindx:
            all_country_data.append({"Country": country, "Rank": rank, "PowerIndex": pwrindx})

    return pd.DataFrame(all_country_data)

country_df = get_country_list()
print(country_df.head())

"""# This cell defines an older version of the get_country_list function. It retrieves the HTML content from the BASE_URL using get_soup, then selects all span elements within div.longFormName to extract only the long-form country names. These names are then collected into a list and finally returned as a Pandas DataFrame with a single column named 'Country'. This version did not extract rank or PowerIndex, which were added in a later iteration."""

def get_country_list():
    soup = get_soup(BASE_URL)

    # This targets ONLY the long-form country names you showed in the HTML
    country_spans = soup.select("div.longFormName > span")

    countries = []
    for span in country_spans:
        country = span.text.strip()
        if country:
            countries.append(country)

    return pd.DataFrame({"Country": countries})

"""# This cell calls the get_country_list function (the older version that only retrieved country names) and stores the result in the country_df DataFrame."""

country_df=get_country_list()

"""# This cell displays the country_df DataFrame, showing the list of countries that were scraped by the previous get_country_list function."""

country_df

"""# This cell calls the get_soup function again with the BASE_URL, similar to a previous cell. It serves as a re-demonstration or a check for the main page's content."""

get_soup('https://www.globalfirepower.com/countries-listing.php')

"""# This cell demonstrates the get_soup function by fetching and printing the BeautifulSoup object for the 'available-military-manpower.php' page, allowing inspection of its HTML structure."""

get_soup('https://www.globalfirepower.com/available-military-manpower.php')

"""# The scrape_metric_page function is designed to extract specific metric data (like population, military personnel, etc.) from individual country metric pages. It takes a URL, uses get_soup to parse the page, and then selects specific elements (country_span and value_span) to build a dictionary of country-to-metric values."""

def scrape_metric_page(url):
    soup = get_soup(url)

    records = soup.select("div.recordsetContainer")
    metric_data = {}

    for record in records:
        # Country name (long form only)
        country_span = record.select_one("div.longFormName > span")

        # Metric value (inside valueContainer)
        value_span = record.select_one("div.valueContainer span span")

        if country_span and value_span:
            country = country_span.text.strip()
            value = value_span.text.strip()
            metric_data[country] = value

    return metric_data

"""# This cell uses the scrape_metric_page function to extract the 'available military manpower' data and then prints the resulting dictionary, showing country names mapped to their respective manpower figures.bold text"""

manpower = scrape_metric_page('https://www.globalfirepower.com/available-military-manpower.php')
print(manpower)

"""# The build_dataset function orchestrates the scraping process for all the additional metrics defined in the OTHER_SOURCES dictionary. It starts by calling get_country_list() to get the initial country list (which now includes 'Rank' and 'PowerIndex'). Then, it iterates through each URL and its corresponding column name in OTHER_SOURCES, scrapes the data for that metric using scrape_metric_page(), and merges this new metric into the master_df DataFrame based on the 'Country' column. A time.sleep(2) is included as a polite delay between requests to avoid overwhelming the website. Finally, it returns the complete master_df."""

def build_dataset():
    master_df = get_country_list()

    print(f"Countries loaded: {len(master_df)}")

    for url, column_name in OTHER_SOURCES.items():
        print(f"Scraping: {column_name}")

        metric_dict = scrape_metric_page(url)

        master_df[column_name] = master_df["Country"].map(metric_dict)

        time.sleep(2)  # polite delay

    return master_df

"""# This main function executes the build_dataset function to gather all the data, then saves the resulting comprehensive DataFrame to a CSV file named military_raw_data.csv. This ensures all scraped data is persistently stored. The if __name__ == "__main__": block ensures that the main() function is called only when the script is executed directly, not when it's imported as a module."""

def main():
    df = build_dataset()
    df.to_csv("military_raw_data.csv", index=False)
    print("✅ military_raw_data.csv created successfully")
if __name__ == "__main__":
    main()

"""# This cell loads the military_raw_data.csv file into a Pandas DataFrame named df and then displays the first few rows (df.head()) to give a quick overview of the raw, uncleaned data."""

df = pd.read_csv("military_raw_data.csv")
print(df.head())
df.info()

"""# This cell performs crucial data cleaning and type conversion. It first loads the military_raw_data.csv into a DataFrame df. Then, it identifies a list of all_potential_numeric_columns that should be numeric. It filters this list to columns_to_clean to only include columns actually present in the DataFrame. For each of these columns, it converts them to string type to handle commas and other non-numeric characters, removes commas and leading/trailing whitespace, and then converts them to numeric types using pd.to_numeric (handling errors by coercing them to NaN).

# Separately, it cleans and converts the 'Defense Budget' column by removing '$' symbols, tab characters (\t), ellipses ('...'), and commas before converting it to a numeric type. This separate treatment is due to its specific formatting. Finally, it saves the cleaned DataFrame back to military_raw_data.csv and displays its head and information to verify the changes.
"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Military Data Analytics/military_raw_data.csv")

# List of columns to clean and convert to numeric, excluding 'Country'
all_potential_numeric_columns = [
    'Rank',
    'PowerIndex',
    'Total Population',
    'Total Military Personnel',
    'Active Personnel',
    'Reserve Personnel',
    'Total Aircraft Strength',
    'Total Helicopter Strength',
    'Total Tank Strength',
    'Total Naval Assets'
] # Added 'Total Naval Assets' here, though it was noted as int64 before, better to be explicit.

# Filter columns_to_clean to only include those actually present in df
columns_to_clean = [col for col in all_potential_numeric_columns if col in df.columns]

# Clean and convert columns to numeric
for col in columns_to_clean:
    # Ensure the column is treated as string before applying .str accessor
    df[col] = df[col].astype(str).str.replace(',', '').str.strip()
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Clean and convert 'Defense Budget' separately due to '$' and '\t' characters
if 'Defense Budget' in df.columns: # Add a check here as well for robustness
    df['Defense Budget'] = df['Defense Budget'].astype(str).str.replace('$', '', regex=False)
    df['Defense Budget'] = df['Defense Budget'].str.replace('\t', '', regex=False)
    df['Defense Budget'] = df['Defense Budget'].str.replace('...', '', regex=False) # Remove ellipsis if present
    df['Defense Budget'] = df['Defense Budget'].str.replace(',', '', regex=False).str.strip()
    df['Defense Budget'] = pd.to_numeric(df['Defense Budget'], errors='coerce')

# Save the cleaned DataFrame back to CSV
df.to_csv("military_raw_data.csv", index=False)

print("Cleaned and converted DataFrame head:")
print(df.head())
print("\nCleaned and converted DataFrame info:")
df.info()

df

"""# This cell uses the describe() method on the DataFrame df to generate descriptive statistics for all numerical columns. This output provides a quick statistical summary, including measures like count, mean, standard deviation, and quartiles, which are essential for understanding the central tendency, dispersion, and shape of the data."""

print(df.describe())

"""# This code, df.isnull().sum(), is used to check for and count missing values in your DataFrame df.

# df.isnull() generates a boolean DataFrame of the same shape as df, where True indicates a missing (NaN) value and False indicates a non-missing value.
# .sum() then counts the number of True values for each column in this boolean DataFrame. The result is a Series where the index is the column name and the value is the total count of missing entries in that column.
# This is a quick and effective way to get an overview of data completeness across your dataset.
"""

df.isnull().sum()

































