# -*- coding: utf-8 -*-
"""module1_&_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibqGcuOtPS0CG1XeDk7dtSRTF4P0ETMa
"""

!pip install requests beautifulsoup4 lxml pandas

# Read URLs from text file
with open("links for military data.txt", "r") as file:
    urls = [line.strip() for line in file if line.strip()]

print("Total URLs loaded:", len(urls))
print("Sample URL:", urls[0])

#To check the exact structure of the URLs
with open("links for military data.txt", "r") as f:
    for i in range(5):
        print(f.readline())

#To extract only the URLs without any labels
import re

with open("links for military data.txt", "r") as file:
    text = file.read()

# Extract valid URLs only
urls = re.findall(r"https?://[^\s'\"<>]+", text)

print("Total clean URLs extracted:", len(urls))
print("Sample URLs:")
for u in urls[:5]:
    print(u)

#Verifying if the URLs are request ready
import requests
from bs4 import BeautifulSoup

headers = {"User-Agent": "Mozilla/5.0"}

test_url = urls[0]
print("Testing URL:", test_url)

response = requests.get(test_url, headers=headers)
print("Status Code:", response.status_code)

soup = BeautifulSoup(response.text, "lxml")
print("Page Title:", soup.title.text)

import requests

headers = {
    "User-Agent": "Mozilla/5.0"
}

test_url = urls[0]
response = requests.get(test_url, headers=headers)

print("Status Code:", response.status_code)
print("Content Length:", len(response.text))

#extract total number of links
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "lxml")

# Find all anchor tags
all_links = soup.find_all("a", href=True)
print("Total links found:", len(all_links))

#extract country urls
country_urls = []

for a in all_links:
    href = a["href"]

    if "country" in href and "military" in href:
        # Convert relative URL to absolute
        if href.startswith("/"):
            href = "https://www.globalfirepower.com" + href

        country_urls.append(href)

# Remove duplicates
country_urls = list(set(country_urls))

print("Total country URLs found:", len(country_urls))
print("Sample country URLs:")
for url in country_urls[:10]:
    print(url)

#picking one country url
test_country_url = country_urls[0]
print(test_country_url)

#requesting for the country page
import requests
from bs4 import BeautifulSoup

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(test_country_url, headers=headers)
print("Status Code:", response.status_code)
print("Content Length:", len(response.text))

#parsing country page html
soup = BeautifulSoup(response.text, "lxml")

print("Page title:")
print(soup.title.text)

#getting metrics labels
'''metric_names = soup.find_all("span", class_="textDark")

print("Total metric labels found:", len(metric_names))
print("Sample metric names:")
for m in metric_names[:10]:
    print(m.text.strip())'''

# Find ALL span elements
all_spans = soup.find_all("span")

print("Total spans found:", len(all_spans))

# Print first 20 span texts and classes
for span in all_spans[:20]:
    print(span.get("class"), "->", span.text.strip())

# Find divs that contain numbers
divs = soup.find_all("div")

for d in divs[:30]:
    text = d.text.strip()
    if any(char.isdigit() for char in text) and len(text) < 40:
        print(text)

soup.find_all(string=lambda text: "Tank" in text)

# Extract all script contents
scripts = soup.find_all("script")

print("Total script tags found:", len(scripts))

script_texts = []

for script in scripts:
    if script.string and "var" in script.string:
        script_texts.append(script.string)

print("Scripts containing JS variables:", len(script_texts))
print(script_texts[0][:500])  # preview

import re

metrics = {}

for script in script_texts:
    matches = re.findall(r"var\s+([a-zA-Z0-9_]+)\s*=\s*([0-9]+)", script)
    for key, value in matches:
        metrics[key] = int(value)

print("Total JS metrics extracted:", len(metrics))
print("Sample metrics:")
for k in list(metrics.keys())[:10]:
    print(k, ":", metrics[k])

country_name = soup.title.text.replace("2025", "").replace("Military Strength", "").strip()

metrics["Country"] = country_name

print(metrics["Country"])

#creating reusable function
import re
import requests
from bs4 import BeautifulSoup

headers = {"User-Agent": "Mozilla/5.0"}

def scrape_country_metrics(url):
    response = requests.get(url, headers=headers, timeout=15)
    soup = BeautifulSoup(response.text, "lxml")

    scripts = soup.find_all("script")
    metrics = {}

    for script in scripts:
        if script.string and "var" in script.string:
            matches = re.findall(r"var\s+([a-zA-Z0-9_]+)\s*=\s*([0-9]+)", script.string)
            for key, value in matches:
                metrics[key] = int(value)

    country_name = soup.title.text.replace("2025", "").replace("Military Strength", "").strip()
    metrics["Country"] = country_name

    return metrics

#now extracting for all the countries
import time
import pandas as pd

all_country_data = []
failed_countries = []

for i, url in enumerate(country_urls):
    try:
        data = scrape_country_metrics(url)
        all_country_data.append(data)
        print(f"Scraped {i+1}/{len(country_urls)}: {data['Country']}")
        time.sleep(1)
    except Exception as e:
        failed_countries.append(url)
        print("Failed:", url)

df_raw = pd.DataFrame(all_country_data)

print("Raw dataset shape:", df_raw.shape)
df_raw.head()

print("Countries scraped:", df_raw["Country"].nunique())
print("Failed countries:", len(failed_countries))

#df_raw.to_csv("military_raw_data.csv", index=False)
df_raw.to_csv("/content/drive/MyDrive/military_raw_data.csv", index=False)

"""**Module 2**"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/military_raw_data.csv")

print("Dataset shape:", df.shape)
df.head()

df.info()

df.columns = (
      df.columns
          .str.strip()
              .str.lower()
              )

df.columns = df.columns.str.replace("js$", "", regex=True)

df.columns

rename_map = {
    "fighter": "fighter_aircraft",
    "attack": "attack_aircraft",
    "transport": "transport_aircraft",
    "trainer": "trainer_aircraft",
    "special": "special_mission_aircraft",
    "tanker": "tanker_aircraft",
    "helicopter": "helicopters",
    "attackhelo": "attack_helicopters",
    "tanks": "tanks",
    "afv": "armored_vehicles",
    "spg": "self_propelled_artillery",
    "artillery": "towed_artillery",
    "mlrs": "rocket_projectors" }

df = df.rename(columns=rename_map)
df.columns

missing_percent = (df.isna().sum() / len(df)) * 100
missing_percent.sort_values(ascending=False)

numeric_cols = df.select_dtypes(include=["float64", "int64"]).columns

df[numeric_cols] = df[numeric_cols].fillna(0)

df["country"].value_counts().head()

df = df.drop_duplicates(subset="country")

df.describe()

cols = ["country"] + [c for c in df.columns if c != "country"]
df = df[cols]

df.head()

print("Final shape:", df.shape)
print("Countries:", df["country"].nunique())
print("Total missing values:", df.isna().sum().sum())

#df.to_csv("military_cleaned.csv", index=False)
df.to_csv("/content/drive/MyDrive/military_cleaned.csv", index=False)