# -*- coding: utf-8 -*-
"""scrape_military_metrics .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Be6uCFBG1Nxw31N6ahSJhLEeX_fqGfYv
"""

import re
import time
import random
import requests
import pandas as pd
from bs4 import BeautifulSoup


# CONFIG

INPUT_FILE = "links for military data.txt"
OUTPUT_FILE = "military_raw_data.csv"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}


# STEP 1: LOAD URL → METRIC

def load_links(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    matches = re.findall(r"'(https://www\.globalfirepower\.com/[^']+)'\s*:\s*'([^']+)'", text)
    return dict(matches)


# STEP 2: SCRAPE ONE PAGE

def scrape_metric(url, metric, data):
    print(f"Scraping {metric}")

    r = requests.get(url, headers=HEADERS, timeout=30)
    soup = BeautifulSoup(r.text, "html.parser")

    records = soup.select("div.recordsetContainer")
    print(f"Records found: {len(records)}")

    for rec in records:
        country_tag = rec.select_one(".longFormName span")
        value_tag = rec.select_one(".valueContainer span span")

        if not country_tag or not value_tag:
            continue

        country = country_tag.get_text(strip=True)
        value = value_tag.get_text(strip=True)

        if country not in data:
            data[country] = {}

        data[country][metric] = value

    time.sleep(random.uniform(1.5, 3))

# -------------------------
# STEP 3: MAIN
# -------------------------
def main():
    links = load_links(INPUT_FILE)
    data = {}

    for url, metric in links.items():
        scrape_metric(url, metric, data)

    df = pd.DataFrame.from_dict(data, orient="index")
    df.index.name = "country"
    df.reset_index(inplace=True)

    df.to_csv(OUTPUT_FILE, index=False)
    print(f"\nSaved {OUTPUT_FILE}")
    print("Countries scraped:", len(df))

# -------------------------
# RUN
# -------------------------
if __name__ == "__main__":
    main()

