# -*- coding: utf-8 -*-
"""Unified Military Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHmt5Bn_coxyS6C--0gHXkFppbFkWtxD
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

BASE_URL = "https://www.globalfirepower.com/countries-listing.php"

OTHER_SOURCES = {
    'https://www.globalfirepower.com/total-population-by-country.php': 'total_population',
        'https://www.globalfirepower.com/available-military-manpower.php': 'total_military_manpower',
        'https://www.globalfirepower.com/manpower-fit-for-military-service.php': 'fit_for_service',
        'https://www.globalfirepower.com/manpower-reaching-military-age-annually.php': 'population_reaching_military_age_annually',
        'https://www.globalfirepower.com/active-military-manpower.php': 'active_personnel',
        'https://www.globalfirepower.com/active-reserve-military-manpower.php': 'reserve_personnel',
        'https://www.globalfirepower.com/manpower-paramilitary.php': 'paramilitary',
        'https://www.globalfirepower.com/aircraft-total.php': 'total_military_aircraft',
        'https://www.globalfirepower.com/aircraft-total-fighters.php': 'fighter_aircraft',
        'https://www.globalfirepower.com/aircraft-total-attack-types.php': 'attack_aircraft',
        'https://www.globalfirepower.com/aircraft-total-transports.php': 'transport_aircraft',
        'https://www.globalfirepower.com/aircraft-total-trainers.php': 'trainer_aircraft',
        'https://www.globalfirepower.com/aircraft-total-special-mission.php': 'special_mission_aircraft',
        'https://www.globalfirepower.com/aircraft-total-tanker-fleet.php': 'tanker_aircraft',
        'https://www.globalfirepower.com/aircraft-helicopters-total.php': 'total_military_helicopters',
        'https://www.globalfirepower.com/aircraft-helicopters-attack.php': 'attack_helicopters',
        'https://www.globalfirepower.com/armor-tanks-total.php': 'tanks',
        'https://www.globalfirepower.com/armor-apc-total.php': 'armored_fighting_vehicles',
        'https://www.globalfirepower.com/armor-self-propelled-guns-total.php': 'self_propelled_artillery',
        'https://www.globalfirepower.com/armor-towed-artillery-total.php': 'towed_artillery',
        'https://www.globalfirepower.com/armor-mlrs-total.php': 'rocket_projectors',
        'https://www.globalfirepower.com/navy-ships.php': 'total_naval_fleet',
        'https://www.globalfirepower.com/navy-force-by-tonnage.php': 'total_naval_fleet_tonnage_mt',
        'https://www.globalfirepower.com/navy-aircraft-carriers.php': 'aircraft_carriers',
        'https://www.globalfirepower.com/navy-helo-carriers.php': 'helicopter_carriers',
        'https://www.globalfirepower.com/navy-submarines.php': 'submarines',
        'https://www.globalfirepower.com/navy-destroyers.php': 'destroyers',
        'https://www.globalfirepower.com/navy-frigates.php': 'frigates',
        'https://www.globalfirepower.com/navy-corvettes.php': 'corvettes',
        'https://www.globalfirepower.com/navy-patrol-coastal-craft.php': 'coastal_patrol_craft',
        'https://www.globalfirepower.com/navy-mine-warfare-craft.php': 'mine_warfare_craft',
        'https://www.globalfirepower.com/defense-spending-budget.php': 'defense_budget_usd',
        'https://www.globalfirepower.com/external-debt-by-country.php': 'external_debt_usd',
        'https://www.globalfirepower.com/purchasing-power-parity.php': 'purchasing_power_parity_usd',
        'https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php': 'foreign_exchange_and_gold_reserves_usd',
        'https://www.globalfirepower.com/major-serviceable-airports-by-country.php': 'total_serviceable_airports',
        'https://www.globalfirepower.com/labor-force-by-country.php': 'labour_force',
        'https://www.globalfirepower.com/major-ports-and-terminals.php': 'major_ports_and_terminals',
        'https://www.globalfirepower.com/merchant-marine-strength-by-country.php': 'total_merchant_marine_fleet',
        'https://www.globalfirepower.com/railway-coverage.php': 'railway_coverage_km',
        'https://www.globalfirepower.com/roadway-coverage.php': 'roadway_coverage_km',
        'https://www.globalfirepower.com/oil-production-by-country.php': 'oil_production_bbl',
        'https://www.globalfirepower.com/oil-consumption-by-country.php': 'oil_consumption_bbl',
        'https://www.globalfirepower.com/proven-oil-reserves-by-country.php': 'proven_oil_reserves_bbl',
        'https://www.globalfirepower.com/natural-gas-production-by-country.php': 'natural_gas_production_cum',
        'https://www.globalfirepower.com/natural-gas-consumption-by-country.php': 'natural_gas_consumption_cum',
        'https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php': 'proven_natural_gas_reserves_cum',
        'https://www.globalfirepower.com/coal-production-by-country.php': 'coal_production_cum',
        'https://www.globalfirepower.com/coal-consumption-by-country.php': 'coal_consumption_mt',
        'https://www.globalfirepower.com/proven-coal-reserves-by-country.php': 'proven_coal_reserves_cum',
        'https://www.globalfirepower.com/square-land-area.php': 'total_land_area_sq_km',
        'https://www.globalfirepower.com/coastline-coverage.php': 'coastline_coverage_km',
        'https://www.globalfirepower.com/border-coverage.php': 'border_coverage_km',
        'https://www.globalfirepower.com/waterway-coverage.php': 'waterway_coverage_km'
}

def get_soup(url):
    response = requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0"},
        timeout=20
    )
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")

get_soup(BASE_URL)

def get_country_list():
    soup = get_soup(BASE_URL)

    # This targets ONLY the long-form country names you showed in the HTML
    country_spans = soup.select("div.longFormName > span")

    countries = []
    for span in country_spans:
        country = span.text.strip()
        if country:
            countries.append(country)

    return pd.DataFrame({"Country": countries})

country_df=get_country_list()
print(country_df)

get_soup('https://www.globalfirepower.com/available-military-manpower.php')

def scrape_metric_page(url):
    soup = get_soup(url)

    records = soup.select("div.recordsetContainer")
    metric_data = {}

    for record in records:
        # Country name (long form only)
        country_span = record.select_one("div.longFormName > span")

        # Metric value (inside valueContainer)
        value_span = record.select_one("div.valueContainer span span")

        if country_span and value_span:
            country = country_span.text.strip()
            value = value_span.text.strip()
            metric_data[country] = value

    return metric_data

manpower = scrape_metric_page('https://www.globalfirepower.com/available-military-manpower.php')
print(manpower)

def build_dataset():
    master_df = get_country_list()

    print(f"Countries loaded: {len(master_df)}")

    for url, column_name in OTHER_SOURCES.items():
        print(f"Scraping: {column_name}")

        metric_dict = scrape_metric_page(url)

        master_df[column_name] = master_df["Country"].map(metric_dict)

        time.sleep(2)  # polite delay

    return master_df

def main():
    df = build_dataset()
    df.to_csv("military_raw_data.csv", index=False)
    print("✅ military_raw_data.csv created successfully")
if __name__ == "__main__":
    main()

df = pd.read_csv("military_raw_data.csv")
print(df.head())

df.info()

df.isnull().sum()

import numpy as np
import pandas as pd

df_raw = pd.read_csv("/content/drive/MyDrive/military_raw_data.csv")
print(df_raw.shape)

required_columns = [
    "Country",

    # Population & Manpower
    "total_population",
    "active_personnel",
    "reserve_personnel",
    "paramilitary",

    # Air Power
    "total_military_aircraft",
    "fighter_aircraft",
    "attack_aircraft",
    "transport_aircraft",
    "trainer_aircraft",
    "special_mission_aircraft",
    "tanker_aircraft",
    "total_military_helicopters",
    "attack_helicopters",

    # Land Forces
    "tanks",
    "armored_fighting_vehicles",
    "self_propelled_artillery",
    "towed_artillery",
    "rocket_projectors",

    # Naval Forces
    "total_naval_fleet",
    "aircraft_carriers",
    "helicopter_carriers",
    "submarines",
    "destroyers",
    "frigates",
    "corvettes",
    "coastal_patrol_craft",
    "mine_warfare_craft",

    # Economy
    "defense_budget_usd",
    "purchasing_power_parity_usd",
    "foreign_exchange_and_gold_reserves_usd",

    # Infrastructure
    "total_serviceable_airports",
    "major_ports_and_terminals",
    "railway_coverage_km",
    "roadway_coverage_km"
]

df = df_raw[required_columns].copy()
print(df.shape)

def clean_numeric(x):
    if pd.isna(x):
        return np.nan

    x = str(x)

    x = (
        x.replace(",", "")
         .replace("$", "")
         .replace("%", "")
         .replace("+", "")
         .replace("km", "")
         .replace("bbl", "")
         .replace("mt", "")
         .replace("cum", "")
         .replace("sq", "")
         .replace("—", "")
         .strip()
    )

    if x.lower() in ["n/a", "na", "", "none"]:
        return np.nan

    return x

numeric_cols = df.columns.drop("Country")

for col in numeric_cols:
    df[col] = df[col].apply(clean_numeric)
    df[col] = pd.to_numeric(df[col], errors="coerce")

zero_fill_cols = [
    "aircraft_carriers",
    "helicopter_carriers",
    "submarines",
    "destroyers",
    "frigates",
    "corvettes",
    "coastal_patrol_craft",
    "mine_warfare_craft",
    "paramilitary",
    "attack_aircraft",
    "tanker_aircraft",
    "trainer_aircraft"
]

df[zero_fill_cols] = df[zero_fill_cols].fillna(0)

df.isna().sum()

df.info()

print(df.head())

df.to_csv("military_cleaned.csv", index=False)

