# -*- coding: utf-8 -*-
"""Module1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXqI3o_nUEnq8JaMZR7_r2WMAvT_wNMO
"""

import requests
from bs4 import BeautifulSoup

BASE_URL = "https://www.globalfirepower.com"
LISTING_URL = f"{BASE_URL}/countries-listing.php"

response = requests.get(LISTING_URL)
soup = BeautifulSoup(response.text, "html.parser")

country_links = []

for a in soup.select("a[href*='country-military-strength-detail.php']"):
    full_url = BASE_URL + "/" + a["href"].lstrip("/")
    country_links.append(full_url)

country_links = list(set(country_links))

with open("country_urls.txt", "w") as f:
    for link in country_links:
        f.write(link + "\n")

print("Total country URLs found:", len(country_links))

import requests
import pandas as pd
from bs4 import BeautifulSoup
import time

with open("country_urls.txt") as f:
    urls = [u.strip() for u in f if u.strip()]

all_data = []

for url in urls:
    print("Scraping:", url)

    try:
        soup = BeautifulSoup(requests.get(url, timeout=15).text, "html.parser")
        data = {}

        # Country name
        h1 = soup.find("h1")
        data["country"] = h1.text.strip() if h1 else "Unknown"

        # Rank & Power Index
        for div in soup.select(".pwrIndx"):
            txt = div.text.lower()
            val = div.find("span").text.strip()
            if "rank" in txt:
                data["rank"] = val
            if "power index" in txt:
                data["power_index"] = val

        # ALL metric rows
        for row in soup.select("li"):
            label = row.find("span", class_="text")
            value = row.find("span", class_="value")

            if label and value:
                key = label.text.strip().lower().replace(" ", "_")
                data[key] = value.text.strip()

        all_data.append(data)
        time.sleep(1)

    except Exception as e:
        print("Failed:", e)

df = pd.DataFrame(all_data)
df.to_csv("military_raw_data.csv", index=False)

print("Countries scraped:", df.shape[0])

import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://www.globalfirepower.com/aircraft-total.php"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers, timeout=15)
soup = BeautifulSoup(response.text, "html.parser")

rows = soup.select(".topRow")
print("Rows found:", len(rows))

data = []

for row in rows:
    # get all visible text elements in order
    texts = [t.strip() for t in row.stripped_strings]

    # Expected format: [rank, country, value]
    if len(texts) >= 3:
        data.append({
            "country": texts[1],
            "total_aircraft": texts[-1]
        })

df = pd.DataFrame(data)

print(df.head())
print(df.shape)

import requests
import pandas as pd
from bs4 import BeautifulSoup
from functools import reduce
from metric_links import other_sources

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36"
}

def scrape_metric(url, metric_name):
    response = requests.get(url, headers=HEADERS, timeout=20)
    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.select(".topRow")
    data = []

    for row in rows:
        texts = [t.strip() for t in row.stripped_strings]
        if len(texts) >= 3:
            data.append({
                "country": texts[1],
                metric_name: texts[-1]
            })

    return pd.DataFrame(data)

dfs = []

for url, metric in other_sources.items():
    print("Scraping:", metric)
    df_metric = scrape_metric(url, metric)
    dfs.append(df_metric)

final_df = reduce(lambda l, r: pd.merge(l, r, on="country", how="outer"), dfs)

final_df.to_csv("military_raw_data.csv", index=False)

print("FINAL SHAPE:", final_df.shape)

