# -*- coding: utf-8 -*-
"""Module2_&_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXRfuH2T8b35nohEY2nTV76kVZ6PSqtZ
"""

import pandas as pd
import re

# Load the file
df = pd.read_csv('military_raw_data (2).csv')

def clean_value(val):
    if pd.isna(val):
        return 0
    # Convert to string to handle any mixed types
    val = str(val)
    # 1. Remove newlines, tabs, and carriage returns
    val = re.sub(r'[\r\n\t]', '', val)
    # 2. Remove non-numeric characters (keep digits and decimal points)
    # This strips things like "$", "km", "bbl", "Cu.M", "mt", and ","
    clean_val = re.sub(r'[^\d.]', '', val)

    # 3. Convert to numeric, return 0 if empty after cleaning
    try:
        return pd.to_numeric(clean_val)
    except:
        return 0

print("Cleaning function ready.")

# List of demographic and manpower columns to clean first
manpower_cols = [
    'total_population', 'total_military_manpower', 'fit_for_service',
    'population_reaching_military_age_annually', 'active_personnel',
    'reserve_personnel', 'paramilitary'
]

for col in manpower_cols:
    df[col] = df[col].apply(clean_value)

print("Demographic and Manpower columns cleaned.")
print(df[manpower_cols].head())

# List of financial and logistical columns
logistics_cols = [
    'defense_budget_usd', 'external_debt_usd', 'purchasing_power_parity_usd',
    'foreign_exchange_and_gold_reserves_usd', 'labour_force',
    'railway_coverage_km', 'roadway_coverage_km', 'total_land_area_sq_km'
]

for col in logistics_cols:
    df[col] = df[col].apply(clean_value)

print("Financial and Logistical columns cleaned.")
# Displaying a sample of the cleaned data
print(df[['country'] + logistics_cols].head())

# Apply cleaning to all columns except 'country'
all_cols = df.columns.tolist()
all_cols.remove('country')

for col in all_cols:
    df[col] = df[col].apply(clean_value)

# Save the progress to a new CSV file
df.to_csv('military_cleaned_data_step1.csv', index=False)
print("All numeric data has been cleaned and saved to 'military_cleaned_data_step1.csv'.")

import requests
import pandas as pd
from bs4 import BeautifulSoup

# Use the same HEADERS from your Module 1 code
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}

def scrape_power_index():
    url = "https://www.globalfirepower.com/countries-listing.php"
    response = requests.get(url, headers=HEADERS, timeout=20)
    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.select(".topRow") # Using your successful selector
    data = []
    for row in rows:
        texts = [t.strip() for t in row.stripped_strings]
        # In the main list, texts usually are: [Rank, Country, PwrIndx: Value]
        if len(texts) >= 3:
            data.append({
                "country": texts[1],
                "power_index": texts[-1].replace('PwrIndx:', '').strip()
            })
    return pd.DataFrame(data)

df_pwr = scrape_power_index()
print(f"Scraped {len(df_pwr)} Power Index entries.")

import requests
import pandas as pd
from bs4 import BeautifulSoup

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

def check_power_index():
    url = "https://www.globalfirepower.com/countries-listing.php"
    print(f"Fetching: {url}...")

    response = requests.get(url, headers=HEADERS, timeout=20)
    soup = BeautifulSoup(response.text, "html.parser")

    # Using your proven .topRow selector
    rows = soup.select(".topRow")
    data = []

    for row in rows:
        texts = [t.strip() for t in row.stripped_strings]
        # texts usually look like: ['1', 'United States', 'PwrIndx: 0.0699']
        if len(texts) >= 3:
            data.append({
                "Rank": texts[0],
                "Country": texts[1],
                "Raw_PwrIndx": texts[-1]
            })

    return pd.DataFrame(data)

# Run verification
df_check = check_power_index()

print("\n--- DATA VERIFICATION (Top 15) ---")
if not df_check.empty:
    print(df_check.head(15).to_string(index=False))
    print(f"\nTotal countries found: {len(df_check)}")
else:
    print("Verification Failed: No rows found. Check if the website has changed its class name from '.topRow'.")

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# =========================
# 1. Load Cleaned Data
# =========================
file_path = "military_cleaned_data_step1.csv"
df = pd.read_csv(file_path)

# =========================
# 2. Select Core Power Features
# =========================
power_features = {
    # Manpower
    "active_personnel": 0.15,
    "reserve_personnel": 0.05,
    "paramilitary_forces": 0.05,

    # Air Power
    "total_military_aircraft": 0.12,
    "fighter_aircraft": 0.08,
    "attack_aircraft": 0.05,

    # Land Power
    "tanks": 0.10,
    "artillery": 0.08,

    # Naval Power
    "total_naval_assets": 0.07,
    "submarines": 0.05,

    # Economy / Budget
    "defense_budget_usd": 0.15
}

features = list(power_features.keys())
weights = list(power_features.values())

# =========================
# 3. Handle Missing Columns (Safety)
# =========================
for col in features:
    if col not in df.columns:
        df[col] = 0

# =========================
# 4. Normalize Features
# =========================
scaler = MinMaxScaler()
df_scaled = df.copy()
df_scaled[features] = scaler.fit_transform(df[features])

# =========================
# 5. Compute Power Index Score
# =========================
df_scaled["power_index_score"] = 0

for col, w in power_features.items():
    df_scaled["power_index_score"] += df_scaled[col] * w

# =========================
# 6. Create Power Index Rank
# =========================
df_scaled["power_index_rank"] = df_scaled["power_index_score"].rank(
    ascending=False,
    method="dense"
).astype(int)

# =========================
# 7. Sort by Rank
# =========================
df_power_index = df_scaled.sort_values("power_index_rank")

# =========================
# 8. Save Output
# =========================
output_file = "Military_Power_Index.csv"
df_power_index.to_csv(output_file, index=False)

print("Power Index file created:", output_file)

# Preview top 10
print(df_power_index[["country", "power_index_score", "power_index_rank"]].head(10))

import pandas as pd

# =========================
# 1. Load both files
# =========================
cleaned_df = pd.read_csv("military_cleaned_data_step1.csv")
power_df = pd.read_csv("Military_Power_Index.csv")

# =========================
# 2. Select only required columns from power index file
# =========================
power_df = power_df[[
    "country",
    "power_index_score",
    "power_index_rank"
]]

# =========================
# 3. Merge datasets
# =========================
final_df = pd.merge(
    cleaned_df,
    power_df,
    on="country",
    how="left"
)

# =========================
# 4. Verify merge
# =========================
print("Final dataset shape:", final_df.shape)
print(final_df[["country", "power_index_score", "power_index_rank"]].head())

# =========================
# 5. Save merged file
# =========================
output_path = "Military_Data_With_Power_Index.csv"
final_df.to_csv(output_path, index=False)

print("Merged file saved:", output_path)

"""MODULE 3

"""

import pandas as pd
import numpy as np

# Load merged data
df = pd.read_csv("Military_Data_With_Power_Index.csv")

# Ensure no divide-by-zero
df["total_population"] = df["total_population"].replace(0, np.nan)

# Calculate total military assets
df["total_military_assets"] = (
    df["tanks"] +
    df["self_propelled_artillery"] +
    df["towed_artillery"]+
    df["total_military_aircraft"] +
    df["total_naval_fleet"]
)

# Assets per capita
df["assets_per_capita"] = df["total_military_assets"] / df["total_population"]

# Assets per million population (dashboard-friendly)
df["assets_per_million_population"] = df["assets_per_capita"] * 1_000_000

# Replace NaN with 0 (optional, for BI tools)
df.fillna(0, inplace=True)

# Save output
output_path = "Military_Data_With_KPIs.csv"
df.to_csv(output_path, index=False)

print("Assets per capita KPI added and file saved.")

import pandas as pd
import numpy as np

# Load your file
df = pd.read_csv("Military_Data_With_Power_Index.csv")

# Safety: avoid divide-by-zero
df["purchasing_power_parity_usd"] = df["purchasing_power_parity_usd"].replace(0, np.nan)

# KPI: Budget to PPP Ratio
df["budget_to_ppp_ratio"] = (
    df["defense_budget_usd"] / df["purchasing_power_parity_usd"]
)

# KPI: Percentage form (better for dashboards)
df["budget_to_ppp_percent"] = df["budget_to_ppp_ratio"] * 100

# Optional: BI-friendly cleanup
df.fillna(0, inplace=True)

# Save output
output_path = "Military_Data_With_KPIs.csv"
df.to_csv(output_path, index=False)

print("Budget-to-PPP KPI added successfully")
print(df[["country", "budget_to_ppp_percent"]].head())

import pandas as pd
import numpy as np

# =========================
# 1. Load BASE file
# =========================
df = pd.read_csv("Military_Data_With_Power_Index.csv")

# =========================
# 2. SAFETY: replace zeros to avoid divide-by-zero
# =========================
df["total_population"] = df["total_population"].replace(0, np.nan)
df["active_personnel"] = df["active_personnel"].replace(0, np.nan)
df["purchasing_power_parity_usd"] = df["purchasing_power_parity_usd"].replace(0, np.nan)

# =========================
# 3. TOTAL MILITARY ASSETS
# =========================
df["total_military_assets"] = (
    df["tanks"] +
    df["self_propelled_artillery"] +
    df["towed_artillery"] +
    df["rocket_projectors"] +
    df["total_military_aircraft"] +
    df["total_naval_fleet"]
)

# =========================
# 4. ASSETS PER CAPITA
# =========================
df["assets_per_capita"] = (
    df["total_military_assets"] / df["total_population"]
)

df["assets_per_million_population"] = (
    df["assets_per_capita"] * 1_000_000
)

# =========================
# 5. BUDGET TO PPP KPI
# =========================
df["budget_to_ppp_ratio"] = (
    df["defense_budget_usd"] / df["purchasing_power_parity_usd"]
)

df["budget_to_ppp_percent"] = (
    df["budget_to_ppp_ratio"] * 100
)

# =========================
# 6. CLEANUP
# =========================
df.fillna(0, inplace=True)

# =========================
# 8. SAVE FINAL KPI FILE
# =========================
output_path = "Military_Data_With_KPIs.csv"
df.to_csv(output_path, index=False)

print("Module 3 KPIs rebuilt successfully")
print("File saved as:", output_path)

# Preview
print(df[[
    "country",
    "assets_per_capita",
    "assets_per_million_population",
    "budget_to_ppp_ratio"
]].head())

import pandas as pd
import numpy as np

# Load latest KPI file (IMPORTANT)
df = pd.read_csv("Military_Data_With_KPIs.csv")

# Safety checks
df["total_land_area_sq_km"] = df["total_land_area_sq_km"].replace(0, np.nan)

# =========================
# 1. TOTAL LAND ASSETS
# =========================
df["total_land_assets"] = (
    df["tanks"] +
    df["armored_fighting_vehicles"] +
    df["self_propelled_artillery"] +
    df["towed_artillery"] +
    df["rocket_projectors"]
)

# =========================
# 2. LAND POWER DENSITY
# =========================
df["land_power_density"] = (
    df["total_land_assets"] / df["total_land_area_sq_km"]
)

# Cleanup
df.fillna(0, inplace=True)

# Save back to SAME file
df.to_csv("Military_Data_With_KPIs.csv", index=False)

print("Land Power KPIs added successfully")
print(df[[
    "country",
    "total_land_assets",
    "land_power_density"
]].head())

import pandas as pd

# Load dataset
file_path = "Military_Data_With_KPIs.csv"
df = pd.read_csv(file_path)

# ---------------- MANPOWER KPIs ----------------

# Total manpower KPI
df["total_manpower_kpi"] = (
    df["active_personnel"] +
    df["reserve_personnel"] +
    df["paramilitary"]
)

# Manpower composition KPIs
df["active_share_kpi"] = df["active_personnel"] / df["total_manpower_kpi"]
df["reserve_share_kpi"] = df["reserve_personnel"] / df["total_manpower_kpi"]
df["paramilitary_share_kpi"] = df["paramilitary"] / df["total_manpower_kpi"]

# Optional: population-normalized manpower KPIs
df["active_per_1000_population"] = df["active_personnel"] / df["total_population"] * 1000
df["reserve_per_1000_population"] = df["reserve_personnel"] / df["total_population"] * 1000
df["paramilitary_per_1000_population"] = df["paramilitary"] / df["total_population"] * 1000
df["total_manpower_per_1000_population"] = df["total_manpower_kpi"] / df["total_population"] * 1000

# ---------------- SAVE BACK ----------------
df.to_csv(file_path, index=False)

print("Manpower KPIs added for ALL countries and saved successfully.")

import pandas as pd

# Load dataset
file_path = "Military_Data_With_KPIs.csv"
df = pd.read_csv(file_path)

# ---------------- TOTAL GROUND POWER KPI ----------------
df["total_ground_power_kpi"] = (
    df["tanks"] +
    df["armored_fighting_vehicles"] +
    df["self_propelled_artillery"] +
    df["towed_artillery"] +
    df["rocket_projectors"]
)

# ---------------- GROUND POWER STRUCTURE KPIs ----------------
df["tanks_share_kpi"] = df["tanks"] / df["total_ground_power_kpi"]
df["afv_share_kpi"] = df["armored_fighting_vehicles"] / df["total_ground_power_kpi"]
df["artillery_share_kpi"] = (
    (df["self_propelled_artillery"] + df["towed_artillery"]) /
    df["total_ground_power_kpi"]
)
df["rocket_share_kpi"] = df["rocket_projectors"] / df["total_ground_power_kpi"]

# ---------------- NORMALIZED KPIs ----------------
df["ground_power_per_1000_population"] = (
    df["total_ground_power_kpi"] / df["total_population"] * 1000
)

df["ground_power_density_per_1000_sq_km"] = (
    df["total_ground_power_kpi"] / df["total_land_area_sq_km"] * 1000
)

# ---------------- SAVE BACK ----------------
df.to_csv(file_path, index=False)

print("Total Ground Power KPIs added and saved successfully.")

import pandas as pd

# Load dataset
file_path = "Military_Data_With_KPIs.csv"
df = pd.read_csv(file_path)

# ---------------- TOTAL AIRCRAFT KPI ----------------
df["total_aircraft_kpi"] = (
    df["fighter_aircraft"] +
    df["attack_aircraft"] +
    df["transport_aircraft"] +
    df["trainer_aircraft"] +
    df["special_mission_aircraft"] +
    df["tanker_aircraft"] +
    df["total_military_helicopters"]
)

# ---------------- AIR POWER STRUCTURE KPIs ----------------
df["fighter_share_kpi"] = df["fighter_aircraft"] / df["total_aircraft_kpi"]
df["attack_share_kpi"] = df["attack_aircraft"] / df["total_aircraft_kpi"]
df["transport_share_kpi"] = df["transport_aircraft"] / df["total_aircraft_kpi"]
df["helicopter_share_kpi"] = df["total_military_helicopters"] / df["total_aircraft_kpi"]

# ---------------- NORMALIZED AIR POWER KPIs ----------------
df["aircraft_per_1000_population"] = (
    df["total_aircraft_kpi"] / df["total_population"] * 1000
)

df["aircraft_density_per_1000_sq_km"] = (
    df["total_aircraft_kpi"] / df["total_land_area_sq_km"] * 1000
)

# ---------------- SAVE BACK ----------------
df.to_csv(file_path, index=False)

print("Total Aircraft KPIs added and saved successfully.")

import pandas as pd

# Load dataset
file_path = "Military_Data_With_KPIs.csv"
df = pd.read_csv(file_path)

# ---------------- TOTAL NAVAL POWER KPI ----------------
df["total_naval_power_kpi"] = (
    df["aircraft_carriers"] +
    df["helicopter_carriers"] +
    df["submarines"] +
    df["destroyers"] +
    df["frigates"] +
    df["corvettes"] +
    df["coastal_patrol_craft"] +
    df["mine_warfare_craft"]
)

# ---------------- NAVAL COMPOSITION KPIs ----------------
df["carrier_share_kpi"] = (
    (df["aircraft_carriers"] + df["helicopter_carriers"]) /
    df["total_naval_power_kpi"]
)

df["submarine_share_kpi"] = df["submarines"] / df["total_naval_power_kpi"]

df["major_surface_share_kpi"] = (
    (df["destroyers"] + df["frigates"]) /
    df["total_naval_power_kpi"]
)

df["light_surface_share_kpi"] = (
    (df["corvettes"] + df["coastal_patrol_craft"]) /
    df["total_naval_power_kpi"]
)

# ---------------- NORMALIZED NAVAL KPIs ----------------
df["naval_power_per_1000_population"] = (
    df["total_naval_power_kpi"] / df["total_population"] * 1000
)

df["naval_power_per_1000_km_coastline"] = (
    df["total_naval_power_kpi"] / df["coastline_coverage_km"] * 1000
)

# ---------------- SAVE BACK ----------------
df.to_csv(file_path, index=False)

print("Total Naval Power KPIs added and saved successfully.")

import pandas as pd

# Load the SAME file you provided
df = pd.read_csv("Military_Data_With_KPIs.csv")

# ---------------------------
# Helper: Min-Max Normalizer
# ---------------------------
def min_max_norm(series):
    return (series - series.min()) / (series.max() - series.min())

# ---------------------------
# Normalized components
# ---------------------------
df["manpower_norm"] = min_max_norm(df["total_military_manpower"])
df["assets_norm"] = min_max_norm(df["total_military_assets"])
df["budget_norm"] = min_max_norm(df["defense_budget_usd"])

# Power index: lower is better → invert before normalizing
df["power_index_norm"] = min_max_norm(1 / df["power_index_score"])

# ---------------------------
# Composite Military Power KPI
# (NO weights, equal contribution)
# ---------------------------
df["composite_military_power_kpi"] = (
    df["manpower_norm"]
    + df["assets_norm"]
    + df["budget_norm"]
    + df["power_index_norm"]
) / 4

# ---------------------------
# Save BACK to file
# ---------------------------
df.to_csv("Military_Data_With_KPIs.csv", index=False)

print("Composite Military Power KPI added to the same file")

import pandas as pd

# Load your file
df = pd.read_csv("Military_Data_With_KPIs.csv")

# ---------------------------
# Helper: Min-Max Normalizer
# ---------------------------
def min_max_norm(series):
    return (series - series.min()) / (series.max() - series.min())

# ---------------------------
# Asset domains
# ---------------------------

# Land assets (already available)
df["land_assets_norm"] = min_max_norm(df["total_land_assets"])

# Air assets
df["air_assets_norm"] = min_max_norm(df["total_military_aircraft"])

# Naval assets (sum of all major naval vessels)
df["total_naval_assets"] = (
    df["submarines"]
    + df["destroyers"]
    + df["frigates"]
    + df["corvettes"]
    + df["coastal_patrol_craft"]
    + df["mine_warfare_craft"]
)

df["naval_assets_norm"] = min_max_norm(df["total_naval_assets"])

# ---------------------------
# Overall Military Assets KPI
# (equal contribution, no weights)
# ---------------------------
df["overall_military_assets_kpi"] = (
    df["land_assets_norm"]
    + df["air_assets_norm"]
    + df["naval_assets_norm"]
) / 3

# ---------------------------
# Save back to SAME file
# ---------------------------
df.to_csv("Military_Data_With_KPIs.csv", index=False)

print("Overall Military Assets KPI added to the same file")

import pandas as pd

# Load your existing file
df = pd.read_csv("Military_Data_With_KPIs.csv")

# ---------------------------
# Helper: Min-Max Normalizer
# ---------------------------
def min_max_norm(series):
    return (series - series.min()) / (series.max() - series.min())

# ---------------------------
# LAND STRENGTH KPI
# ---------------------------
df["land_strength_kpi"] = min_max_norm(df["total_land_assets"])

# ---------------------------
# AIR STRENGTH KPI
# ---------------------------
df["air_strength_kpi"] = min_max_norm(df["total_military_aircraft"])

# ---------------------------
# NAVAL STRENGTH KPI
# ---------------------------
df["total_naval_assets"] = (
    df["submarines"]
    + df["destroyers"]
    + df["frigates"]
    + df["corvettes"]
    + df["coastal_patrol_craft"]
    + df["mine_warfare_craft"]
)

df["naval_strength_kpi"] = min_max_norm(df["total_naval_assets"])

# ---------------------------
# Save BACK to same file
# ---------------------------
df.to_csv("Military_Data_With_KPIs.csv", index=False)

print("Land, Air, and Naval Strength KPIs added successfully")

import pandas as pd

# Load your existing file
df = pd.read_csv("Military_Data_With_KPIs.csv")

# ---------------------------
# Helper: Min-Max Normalizer
# ---------------------------
def min_max_norm(series):
    return (series - series.min()) / (series.max() - series.min())

# ---------------------------
# Normalize geographic exposures
# ---------------------------
df["border_exposure_norm"] = min_max_norm(df["border_coverage_km"])
df["coastline_exposure_norm"] = min_max_norm(df["coastline_coverage_km"])
df["waterway_exposure_norm"] = min_max_norm(df["waterway_coverage_km"])

# ---------------------------
# Geographic Defense Burden KPI
# ---------------------------
df["geographic_defense_burden_kpi"] = (
    df["border_exposure_norm"]
    + df["coastline_exposure_norm"]
    + df["waterway_exposure_norm"]
) / 3

# ---------------------------
# Save BACK to same file
# ---------------------------
df.to_csv("Military_Data_With_KPIs.csv", index=False)

print("Geographic Defense Burden KPI added successfully")