# -*- coding: utf-8 -*-
"""generate_kpis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6NSIRD881bj6Y-CG2ihYrr3P5MScjl5
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

file_path = "/content/drive/MyDrive/military_cleaned.csv"
df = pd.read_csv(file_path)

# Standardize columns
df.columns = df.columns.str.lower()

"""1. Power Index Rank Gap"""

# Power Rank (lower pwr_index = stronger)
df["power_rank"] = df["pwr_index"].rank(method="min", ascending=True)

# Population Rank (higher population = stronger)
df["population_rank"] = df["total_population"].rank(method="min", ascending=False)

# KPI 1: Power Index Rank Gap
df["power_index_rank_gap"] = df["population_rank"] - df["power_rank"]

"""2. Assets per Capita"""

df["assets_per_capita"] = (
    df["total_military_aircraft"]
    + df["tanks"]
    + df["total_naval_fleet"]
    + df["total_military_helicopters"]
) / df["total_population"]

"""3. budget_to_gdp_ratio"""

df["budget_to_gdp_ratio"] = (
    df["defense_budget_usd"] / df["purchasing_power_parity_usd"]
)

"""4. budget_per_soldier"""

df["budget_per_soldier"] = (
    df["defense_budget_usd"] / df["total_military_manpower"]
)

"""5. air_power_density"""

df["air_power_density"] = (
    df["total_military_aircraft"] / df["total_population"]
)

"""6. military_participation_ratio"""

df["military_participation_ratio"] = (
    df["total_military_manpower"] / df["total_population"]
)
df.replace([np.inf, -np.inf], np.nan, inplace=True)

df.to_csv("military_final.csv", index=False)

"""For NATO
"https://www.nato.int/en/about-us/organization/nato-member-countries"
"""

import requests
from bs4 import BeautifulSoup

df["country"] = df["country"].str.strip()

url = "https://www.nato.int/en/about-us/organization/nato-member-countries"

response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

nato_countries = []

country_tags = soup.find_all("p", class_="cie-country__name")

for tag in country_tags:
    country_name = tag.get_text(strip=True)
    nato_countries.append(country_name)

print(nato_countries)
print("Total NATO countries:", len(nato_countries))

df["is_nato"] = df["country"].apply(
    lambda x: 1 if x in nato_countries else 0
)

df["is_nato"].value_counts()

df.to_csv("military_final.csv", index=False)

"""Continent and Region "https://statisticstimes.com/geography/countries-by-continents.php"
"""

url = "https://statisticstimes.com/geography/countries-by-continents.php"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

continent_dict = {}
region_dict = {}

table = soup.find("table", id="table_id")
tbody = table.find("tbody")

for row in tbody.find_all("tr"):
    cols = row.find_all("td")
    if len(cols) < 7:
        continue

    country = cols[1].get_text(strip=True)
    region = cols[4].get_text(strip=True)
    continent = cols[6].get_text(strip=True)

    region_dict[country] = region
    continent_dict[country] = continent

df["region"] = df["country"].map(region_dict)
df["continent"] = df["country"].map(continent_dict)

df["region"] = df["region"].fillna("Unknown")
df["continent"] = df["continent"].fillna("Unknown")

print("Unmatched countries:")
print(df[df["continent"] == "Unknown"]["country"])

manual_geo = {
    "United States": ("Northern America", "North America"),
    "Russia": ("Eastern Europe", "Europe"),
    "South Korea": ("Eastern Asia", "Asia"),
    "North Korea": ("Eastern Asia", "Asia"),
    "United Kingdom": ("Northern Europe", "Europe"),
    "Turkiye": ("Western Asia", "Asia"),
    "Iran": ("Southern Asia", "Asia"),
    "Vietnam": ("South-Eastern Asia", "Asia"),
    "Syria": ("Western Asia", "Asia"),
    "Bolivia": ("South America", "South America"),
    "Tanzania": ("Eastern Africa", "Africa"),
    "Ivory Coast": ("Western Africa", "Africa"),
    "Laos": ("South-Eastern Asia", "Asia"),
    "Republic of the Congo": ("Middle Africa", "Africa"),
    "Moldova": ("Eastern Europe", "Europe"),
    "Venezuela": ("South America", "South America"),
    "Taiwan": ("Eastern Asia", "Asia"),
    "Kosovo": ("Southern Europe", "Europe"),
    "Beliz": ("Central America", "North America")
}

for country, (region, continent) in manual_geo.items():
    df.loc[df["country"] == country, "region"] = region
    df.loc[df["country"] == country, "continent"] = continent

print(df[df["continent"] == "Unknown"]["country"])

df.to_csv("military_final.csv", index=False)