# -*- coding: utf-8 -*-
"""scrape_military_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVZNJD0Tl5_kaeikCPV-FHgeChC6D6qd
"""

from bs4 import BeautifulSoup
import requests

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
URLS = {
        'https://www.globalfirepower.com/countries-listing.php':'pwr_index',
        'https://www.globalfirepower.com/total-population-by-country.php': 'total_population',
        'https://www.globalfirepower.com/available-military-manpower.php': 'total_military_manpower',
        'https://www.globalfirepower.com/manpower-fit-for-military-service.php': 'fit_for_service',
        'https://www.globalfirepower.com/manpower-reaching-military-age-annually.php': 'population_reaching_military_age_annually',
        'https://www.globalfirepower.com/active-military-manpower.php': 'active_personnel',
        'https://www.globalfirepower.com/active-reserve-military-manpower.php': 'reserve_personnel',
        'https://www.globalfirepower.com/manpower-paramilitary.php': 'paramilitary',
        'https://www.globalfirepower.com/aircraft-total.php': 'total_military_aircraft',
        'https://www.globalfirepower.com/aircraft-total-fighters.php': 'fighter_aircraft',
        'https://www.globalfirepower.com/aircraft-total-attack-types.php': 'attack_aircraft',
        'https://www.globalfirepower.com/aircraft-total-transports.php': 'transport_aircraft',
        'https://www.globalfirepower.com/aircraft-total-trainers.php': 'trainer_aircraft',
        'https://www.globalfirepower.com/aircraft-total-special-mission.php': 'special_mission_aircraft',
        'https://www.globalfirepower.com/aircraft-total-tanker-fleet.php': 'tanker_aircraft',
        'https://www.globalfirepower.com/aircraft-helicopters-total.php': 'total_military_helicopters',
        'https://www.globalfirepower.com/aircraft-helicopters-attack.php': 'attack_helicopters',
        'https://www.globalfirepower.com/armor-tanks-total.php': 'tanks',
        'https://www.globalfirepower.com/armor-apc-total.php': 'armored_fighting_vehicles',
        'https://www.globalfirepower.com/armor-self-propelled-guns-total.php': 'self_propelled_artillery',
        'https://www.globalfirepower.com/armor-towed-artillery-total.php': 'towed_artillery',
        'https://www.globalfirepower.com/armor-mlrs-total.php': 'rocket_projectors',
        'https://www.globalfirepower.com/navy-ships.php': 'total_naval_fleet',
        'https://www.globalfirepower.com/navy-force-by-tonnage.php': 'total_naval_fleet_tonnage_mt',
        'https://www.globalfirepower.com/navy-aircraft-carriers.php': 'aircraft_carriers',
        'https://www.globalfirepower.com/navy-helo-carriers.php': 'helicopter_carriers',
        'https://www.globalfirepower.com/navy-submarines.php': 'submarines',
        'https://www.globalfirepower.com/navy-destroyers.php': 'destroyers',
        'https://www.globalfirepower.com/navy-frigates.php': 'frigates',
        'https://www.globalfirepower.com/navy-corvettes.php': 'corvettes',
        'https://www.globalfirepower.com/navy-patrol-coastal-craft.php': 'coastal_patrol_craft',
        'https://www.globalfirepower.com/navy-mine-warfare-craft.php': 'mine_warfare_craft',
        'https://www.globalfirepower.com/defense-spending-budget.php': 'defense_budget_usd',
        'https://www.globalfirepower.com/external-debt-by-country.php': 'external_debt_usd',
        'https://www.globalfirepower.com/purchasing-power-parity.php': 'purchasing_power_parity_usd',
        'https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php': 'foreign_exchange_and_gold_reserves_usd',
        'https://www.globalfirepower.com/major-serviceable-airports-by-country.php': 'total_serviceable_airports',
        'https://www.globalfirepower.com/labor-force-by-country.php': 'labour_force',
        'https://www.globalfirepower.com/major-ports-and-terminals.php': 'major_ports_and_terminals',
        'https://www.globalfirepower.com/merchant-marine-strength-by-country.php': 'total_merchant_marine_fleet',
        'https://www.globalfirepower.com/railway-coverage.php': 'railway_coverage_km',
        'https://www.globalfirepower.com/roadway-coverage.php': 'roadway_coverage_km',
        'https://www.globalfirepower.com/oil-production-by-country.php': 'oil_production_bbl',
        'https://www.globalfirepower.com/oil-consumption-by-country.php': 'oil_consumption_bbl',
        'https://www.globalfirepower.com/proven-oil-reserves-by-country.php': 'proven_oil_reserves_bbl',
        'https://www.globalfirepower.com/natural-gas-production-by-country.php': 'natural_gas_production_cum',
        'https://www.globalfirepower.com/natural-gas-consumption-by-country.php': 'natural_gas_consumption_cum',
        'https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php': 'proven_natural_gas_reserves_cum',
        'https://www.globalfirepower.com/coal-production-by-country.php': 'coal_production_cum',
        'https://www.globalfirepower.com/coal-consumption-by-country.php': 'coal_consumption_mt',
        'https://www.globalfirepower.com/proven-coal-reserves-by-country.php': 'proven_coal_reserves_cum',
        'https://www.globalfirepower.com/square-land-area.php': 'total_land_area_sq_km',
        'https://www.globalfirepower.com/coastline-coverage.php': 'coastline_coverage_km',
        'https://www.globalfirepower.com/border-coverage.php': 'border_coverage_km',
        'https://www.globalfirepower.com/waterway-coverage.php': 'waterway_coverage_km'

}
HEADERS = {
    "User-Agent": "Mozilla/5.0"
}
all_data = {}

for url, metric in URLS.items():
    try:
        response = requests.get(url, headers=HEADERS, timeout=20)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, "html.parser")
        records = soup.find_all("div", class_="recordsetContainer")

        for record in records:
            country_tag = record.find("div", class_="longFormName")

            # Correct pwr_index parsing for base URL
            if metric == 'pwr_index':
                value_tag = record.find("div", class_="pwrIndxContainer")
            else:
                value_tag = record.find("div", class_="valueContainer")

            if not country_tag or not value_tag:
                continue

            country = country_tag.text.strip()
            # get <span> if exists, else text
            value_span = value_tag.find("span")
            value = value_span.text.strip() if value_span else value_tag.text.strip()

            if country not in all_data:
                all_data[country] = {}

            all_data[country][metric] = value

        time.sleep(1)

    except Exception:
        pass

df = pd.DataFrame.from_dict(all_data, orient="index")
df.reset_index(inplace=True)
df.rename(columns={"index": "Country"}, inplace=True)
df.to_csv("military_raw_data.csv", index=False)

print("No of rows:",df.shape[0])
print("No of columns:",df.shape[1])

print(df['Country'])

print(df.columns)

url_status = {}  # to store success/failure for each URL

for url, metric in URLS.items():
    try:
        response = requests.get(url, headers=HEADERS, timeout=20)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, "html.parser")
        records = soup.find_all("div", class_="recordsetContainer")

        if not records:
            url_status[url] = "No records found"
            continue

        for record in records:
            country_tag = record.find("div", class_="longFormName")
            value_tag = record.find("div", class_="pwrIndxContainer") if metric == "pwr_index" else record.find("div", class_="valueContainer")

            if country_tag and value_tag:
                country = country_tag.text.strip()
                value_span = value_tag.find("span")
                value = value_span.text.strip() if value_span else value_tag.text.strip()

                if country not in all_data:
                    all_data[country] = {}
                all_data[country][metric] = value

        url_status[url] = "Success"
        time.sleep(1)

    except Exception as e:
        url_status[url] = f"Failed: {str(e)}"
total_urls = len(URLS)
successful_urls = sum(1 for status in url_status.values() if status == "Success")
success_rate = (successful_urls / total_urls) * 100

print(f"URL Success Rate: {success_rate:.2f}%")
if success_rate >= 95:
    print("≥95% URLs scraped successfully")
else:
    print("Less than 95% URLs scraped successfully")


countries_scraped = df.shape[0]
print(f"Total countries scraped: {countries_scraped}")

# check for missing metrics
missing_metrics = df.isna().sum()
print("\nMissing metric counts per column:")
print(missing_metrics)