# -*- coding: utf-8 -*-
"""generate_kpis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UbRWKUIjvZ8-H5Gqdf0RTFs04AJZevM
"""

import pandas as pd
import numpy as np

# -----------------------------
# load the module 2 dataset
# -----------------------------
df = pd.read_csv("military_cleaned.csv")
df.columns = df.columns.str.lower().str.strip()

# -----------------------------
#  KPI 1: ASSETS PER CAPITA
# -----------------------------
df["total_military_assets"] = (
    df["tanks"]
    + df["armored_fighting_vehicles"]
    + df["total_military_aircraft"]
    + df["total_military_helicopters"]
    + df["total_naval_fleet"]
)

df["assets_per_capita"] = (
    df["total_military_assets"]
    / df["total_population"].replace(0, np.nan)
)

# -----------------------------
#  KPI 2: BUDGET TO GDP RATIO
# -----------------------------
df["budget_to_gdp_ratio"] = (
    df["defense_budget_usd"]
    / df["purchasing_power_parity_usd"].replace(0, np.nan)
)

# -----------------------------
# POWER INDEX calculation
# -----------------------------
df["manpower_index"] = (
    df["active_personnel"]
    + df["reserve_personnel"]
    + df["paramilitary"]
)

df["air_power_index"] = (
    df["total_military_aircraft"]
    + df["total_military_helicopters"]
)

df["land_power_index"] = (
    df["tanks"]
    + df["armored_fighting_vehicles"]
    + df["self_propelled_artillery"]
    + df["towed_artillery"]
    + df["rocket_projectors"]
)

df["naval_power_index"] = df["total_naval_fleet"]

df["economic_power_index"] = (
    df["defense_budget_usd"]
    + df["foreign_exchange_and_gold_reserves_usd"]
)

power_cols = [
    "manpower_index",
    "air_power_index",
    "land_power_index",
    "naval_power_index",
    "economic_power_index",
]

for c in power_cols:
    df[c + "_norm"] = df[c] / df[c].max()

df["overall_power_index"] = df[
    [c + "_norm" for c in power_cols]
].mean(axis=1)

# -----------------------------
#  KPI 3: RANK + RANK GAP
# -----------------------------
df["overall_rank"] = (
    df["overall_power_index"]
    .rank(ascending=False, method="dense")
    .astype(int)
)

df["power_index_rank_gap"] = (
    df["overall_rank"] - df["overall_rank"].min()
)

# -----------------------------
# METADATA ENRICHMENT
# -----------------------------
nato_members = [
    "United States","Canada","United Kingdom","France","Germany","Italy",
    "Spain","Portugal","Netherlands","Belgium","Norway","Denmark","Poland",
    "Czech Republic","Slovakia","Hungary","Romania","Bulgaria","Greece",
    "Turkey","Estonia","Latvia","Lithuania","Finland","Sweden","Iceland",
    "Luxembourg","Slovenia","Croatia","Albania","Montenegro","North Macedonia"
]
df["is_nato"] = df["country"].isin(nato_members).astype(int)

continent_map = {
    "United States":"North America",
    "Canada":"North America",
    "China":"Asia",
    "India":"Asia",
    "Russia":"Europe",
    "Germany":"Europe",
    "France":"Europe",
    "United Kingdom":"Europe",
    "Japan":"Asia",
    "Australia":"Oceania"
}
df["continent"] = df["country"].map(continent_map).fillna("Other")

region_map = {
    "North America":"Americas",
    "South America":"Americas",
    "Europe":"Europe",
    "Asia":"Asia",
    "Oceania":"Oceania",
    "Africa":"Africa"
}
df["region"] = df["continent"].map(region_map).fillna("Other")

# -----------------------------
# LONG FORMAT
# -----------------------------
long_df = df.melt(
    id_vars=["country","continent","region","is_nato","overall_rank"],
    value_vars=[
        "assets_per_capita",
        "budget_to_gdp_ratio",
        "overall_power_index",
        "power_index_rank_gap"
    ],
    var_name="kpi_name",
    value_name="kpi_value"
)

# -----------------------------
# EXPORT to  SINGLE XLSX
# -----------------------------
with pd.ExcelWriter("military_final.xlsx") as writer:

    df.to_excel(writer, sheet_name="Wide_Data", index=False)
    long_df.to_excel(writer, sheet_name="Long_Data", index=False)

